[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
